# project              cluster           location      node-pool   daytime-node-count
example-project-dev    example-dev-gke   asia-south1   general     1
example-project-uat    example-uat-gke   asia-south1   general     2
